apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: management
  namespace: production
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 50%
  progressDeadlineSeconds: 10
  template:
    metadata:
      labels:
        app: management
    spec:
      containers:
        - image: rajagupt/management:latest
          name: management
          imagePullPolicy: Always
          ports:
            - name: management
              containerPort: 8083
          env:
            - name: sagaEnabled
              value: "1"
            - name: userms.hostname
              value: "http://user"
            - name: userms.port
              value: "8080"
