apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spark
  namespace: production
spec:
  replicas: 1
  progressDeadlineSeconds: 10
  template:
    metadata:
      labels:
        app: spark
    spec:
      containers:
        - image: bitnami/spark:2
          name: spark
          env:
            - name: SPARK_MODE
              value: "master"
            - name: SPARK_RPC_AUTHENTICATION_ENABLED
              value: "no"
            - name: SPARK_RPC_ENCRYPTION_ENABLED
              value: "no"            
            - name: SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED
              value: "no"            
            - name: SPARK_SSL_ENABLED
              value: "no"
          imagePullPolicy: Always
          ports:
            - name: spark-ui
              containerPort: 8080
            - name: spark-master
              containerPort: 7077              
status: {}
